version: 2

jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04

    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            echo $HOME
            make prepare
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install
          command: make install
      - run:
          name: Build
          command: make build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
